### PR TITLE
Fix icons wording when there is one item (IconSetPreviewFooter)

### LINKED ISSUE #230: Fix `icons` wording when there is one item
image

### PR DESCRIPTION
**Pull request by batin**
Closes #230

### CODE REVIEW

File: src/components/IconSetPreviewFooter.tsx [hunk 1]
```diff
@@ -72,7 +72,7 @@ const IconSetPreviewFooter = ({
     <>
       <div className="min-h-20 z-10 flex flex-col items-center justify-between gap-3 divide-neutral-300 bg-neutral-100 p-4 dark:bg-neutral-800 sm:flex-row">
         <div className="text-xs text-neutral-500">
-          {`${icons.length} icons`}
+          {`${icons.length} ${icons.length === 1 ? "icon" : "icons"}`}
```
Comment (aykutkardas) [inline src/components/IconSetPreviewFooter.tsx]: This condition could be better.

`icons.length > 1 ? 'icons' : 'icon'`

Comment (batin) [reply src/components/IconSetPreviewFooter.tsx]: Yes! I've just committed the fix

**Review by aykutkardas — APPROVED** [review]
